# Python 機械学習クックブック

In [3]:
import numpy as np

## 行列の作成

In [4]:
# 3✕2行列を作成
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print(matrix)

[[1 2]
 [3 4]
 [5 6]]


## 要素の選択

In [11]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 2行目,1列目の値を取得
print(matrix[1, 0])

# スライスも使える
print(matrix[:, 0])

3
[1 3 5]


## 行列の性質を取得する

In [9]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 行数・列数を取得
print(matrix.shape)

# 要素数(行数✕列数)を取得
print(matrix.size)

# 次元数を表示
print(matrix.ndim)

(3, 2)
6
2


## 最大値と最小値を見つける

In [16]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 最小値を取得
print(np.min(matrix))

# 最大値を取得
print(np.max(matrix))

# 各列や行に対して処理も可能
print(np.min(matrix,axis=0))
print(np.min(matrix,axis=1))

1
6
[1 2]
[1 3 5]


## 平均・分散・標準偏差の計算

In [18]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 平均値を取得
print(np.mean(matrix))

# 分散を取得
print(np.var(matrix))

# 標準偏差を算出
print(np.std(matrix))

# 各軸に対して処理も可能
print(np.mean(matrix,axis=0))
print(np.var(matrix,axis=1))

3.5
2.9166666666666665
1.707825127659933
[3. 4.]
[0.25 0.25 0.25]


## 配列形状の変更

In [26]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix)

# 2✕3行列に形状変換
print(matrix.reshape(2, 3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


## 行列の転置

In [29]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix)

print(matrix.T)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


## 行列のフラット化

In [32]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix.flatten())

[1 2 3 4 5 6]


## 行列のランク

In [33]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(np.linalg.matrix_rank(matrix))

2


## 行列式の計算

In [35]:
matrix = np.array([[1, 2], [3, 4]])
np.linalg.det(matrix)

-2.0000000000000004

## 行列の対角要素の取得

In [37]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 対角要素を取得
print(matrix.diagonal())

# 対角要素の合計を返す
print(matrix.trace())


[1 5 9]
15


## 固有値・固有ベクトル

In [38]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
# 固有値
print(eigenvalues)

# 固有ベクトル
print(eigenvectors)


[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## 行列の計算

In [43]:
matrix_A = np.array([1, 2, 3])
matrix_B = np.array([4, 5, 6])

# 内積の計算
print(np.dot(matrix_A, matrix_B))

# 加算
print(np.add(matrix_A, matrix_B))

# 減算
print(np.subtract(matrix_A, matrix_B))

# 要素ごとの乗算
print(matrix_A*matrix_B)


32
[5 7 9]
[-3 -3 -3]
[ 4 10 18]


## 逆行列の算出

In [47]:
matrix = np.array([[1, 2], [3, 4]])

# 逆行列の算出
print(np.linalg.inv(matrix))

[[-2.   1. ]
 [ 1.5 -0.5]]


## 乱数の生成

In [54]:
# シード値の設定
np.random.seed(42)

# 0.0～1.0のランダムな数値を生成する
print(np.random.random(4))

# 0～10のランダムな整数値を生成する
print(np.random.randint(0, 11, 4))

# 0.0～10.0のランダムな数値を生成する
print(np.random.uniform(0.0, 1.0, 4))

# 平均0,標準偏差1の正規分布から数値を生成する
print(np.random.normal(0, 1, 4))

#

[0.37454012 0.95071431 0.73199394 0.59865848]
[6 9 2 6]
[0.05808361 0.86617615 0.60111501 0.70807258]
[-0.46947439  0.54256004 -0.46341769 -0.46572975]
