# Python 機械学習クックブック

In [3]:
import numpy as np

## 行列の作成

In [4]:
# 3✕2行列を作成
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print(matrix)

[[1 2]
 [3 4]
 [5 6]]


## 要素の選択

In [11]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 2行目,1列目の値を取得
print(matrix[1, 0])

# スライスも使える
print(matrix[:, 0])

3
[1 3 5]


## 行列の性質を取得する

In [9]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 行数・列数を取得
print(matrix.shape)

# 要素数(行数✕列数)を取得
print(matrix.size)

# 次元数を表示
print(matrix.ndim)

(3, 2)
6
2


## 最大値と最小値を見つける

In [16]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 最小値を取得
print(np.min(matrix))

# 最大値を取得
print(np.max(matrix))

# 各列や行に対して処理も可能
print(np.min(matrix,axis=0))
print(np.min(matrix,axis=1))

1
6
[1 2]
[1 3 5]


## 平均・分散・標準偏差の計算

In [18]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# 平均値を取得
print(np.mean(matrix))

# 分散を取得
print(np.var(matrix))

# 標準偏差を算出
print(np.std(matrix))

# 各軸に対して処理も可能
print(np.mean(matrix,axis=0))
print(np.var(matrix,axis=1))

3.5
2.9166666666666665
1.707825127659933
[3. 4.]
[0.25 0.25 0.25]
